Version: Release1.7.0 #Version. 版本号
Language: en_US.properties #LanguageFile,Support English and chinese,chinese is zh_CN.properties. 语言文件，支持英文和中文，中文填 zh_CN.properties
HttpUrl: https://data-seed-prebsc-1-s1.binance.org:8545/ #blockchain httpUrl. 区块链的HTTP和端口连接
ExplorerUrl: §ahttps://testnet.bscscan.com/tx/ #Blockchain explorer url. 区块链浏览器的地址
Symbol: BNB #NaiveToken Symbol. 原链代币的标志
ChainName: "Binance Smart Chain Testnet" #chainname 链名
ChainID: 97 #blockchain id 链id.
OnPlayerLoginRegisterWallet: true #whether to create a wallet when the player logs in, true = yes. 是否在玩家登录时创建钱包，true为是
LegacyWalletGenerator: false #Whether to enable legacy wallet generator, BIP39 Wallet. If you are in old minecraft version like 1.8. enable this true = yes. 是否使用老式生成方式生成钱包. true为是 如果你是老版本1.8出现了错误打开这个
playerCanImportTheyOwnWallet: false #Whether to enable players to enter their own wallets, true = yes.是否允许玩家自行输入钱包. true为是
playerCanTradeEachOther: false #whether to enable players to trade each others: /wallet trade, true = yes.是否允许玩家相互使用物品交易命令 /wallet trade ,true为是.
TradeWorldLimit: false #whether to enable trade world limit. In list you cannot trade in that world. 是否开启交易世界限制如果开启，下列世界均无法使用交易功能.
LimitedWorld:
  - world
  - world_nether
  - world_the_end
TradeAmountLimit: 0 #trade amount limit. Number of transactions player can sent, 0 is close limit. 交易数量限制. 玩家能够发送多少笔交易, 0 是关闭限制.
EnableCommandFilter: true #whether to enable command filter. (Now only /wallet import <privatekey>) true = yes. 是否开启命令屏蔽, (目前只生效于 /wallet import <私钥>) true为是.
EnableErrorPrint: false #whether to print error message. true = yes. 是否开启错误显示 true为是.
EnableGeneralChecker: true #whether to enable general checker. (balance checker...) true = yes. 是否开启常规检测. (金额检测...) true为是.
EnablePlaceHolderAPI: true #whether to enable PlaceHolderAPI support. (%sftfinance_ethbalance%) true = yes. 是否开启PlaceHolderAPI支持.(%sftfinance_ethbalance%) true为是.
IsMysql: false #whether to use mysql database. 是否使用Mysql数据库.
MysqlUrl: mysql://localhost:3306/SFTFinance #Mysql Url. Mysql 链接地址.
MysqlUser: root #Mysql user. Mysql 用户
MysqlPassword: 1234 #Mysql password. Mysql 用户密码