name: SFTFinance
main: com.sixfivetwo.sftfinance.Main
version: Release1.7.0
softdepend: [PlaceholderAPI]
commands:
  wallet:
    aliases:
    usage: "/wallet"
    description: "Get your wallet balances"